title: Suriname Geospatial Capacity Building Workshops
description: The contents page of the geospatial training workshops in Suriname
baseurl: "/suriname-training" # the subpath of your site, e.g. /blog
url: "https://servir-amazonia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/transparent-logos.png"

remote_theme: just-the-docs/just-the-docs
